---
application:
  name: "annoyingnuisance"
  project: "annoyingbot"
  organization: "QoveryCommunity"
routers:
- name: "main-annoyingnuisance"
  routes:
  - application_name: "annoyingnuisance"
    paths:
    - "/*"
